// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARArsQkZpyYJZQ7tu8_aOtrpq7cTwnsIU',
    appId: '1:957711199483:web:9ba7bed44104b5f726d45e',
    messagingSenderId: '957711199483',
    projectId: 'dentmind-8da6e',
    authDomain: 'dentmind-8da6e.firebaseapp.com',
    storageBucket: 'dentmind-8da6e.appspot.com',
    measurementId: 'G-W2ZJXD4YDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT5jVYLmclJ020X2xbu3up628wygxfGB0',
    appId: '1:957711199483:android:21464a29b2326bbe26d45e',
    messagingSenderId: '957711199483',
    projectId: 'dentmind-8da6e',
    storageBucket: 'dentmind-8da6e.appspot.com',
  );
}
